library(quantmod)
nmlist<-c('XLK','XLV','XLF','XLY','XLP','XLU','XLE','XLC',
          'XLI','XLRE','XLB')
returns<-list()
for (i in 1:length(nmlist)){
  getSymbols(nmlist[i],from='2018-07-31',to='2021-10-1')
  x<-dailyReturn(Ad(get(nmlist[i])))
  returns[[i]]<-x
}
rt<-cbind(returns[[1]],returns[[2]],returns[[3]],returns[[4]],
          returns[[5]],returns[[6]],returns[[7]],returns[[8]],
          returns[[9]],returns[[10]],returns[[11]])
class(rt)
rt<-round(rt,digits=4)
colnames(rt)<-nmlist
View(rt)

install.packages('fPortfolio')
library(fPortfolio)
returns_series<-as.timeSeries(rt)
specEF<-portfolioSpec()
setRiskFreeRate(specEF)<-0.08/252
frontier<-portfolioFrontier(returns_series,specEF)
frontier_points<-frontierPlot(frontier,pch=19)
EF_point<-singleAssetPoints(frontier,pch=19,cex=1.5,col='orange')
text(y=EF_point[,'targetReturn'],x=EF_point[,'targetRisk'],
     labels=row.names(EF_point),pos=4,cex=1)
minvariancePoints(frontier,pch=19,cex=1.5,col='red')
tangencyLines(frontier,lty=1,lwd=4,col='blue')
tangencyPoints(frontier,pch=19,cex=1.5,col='green')

library(PerformanceAnalytics)
m_xlk<-mean(rt[,'XLK'])
s_xlk<-sd(rt[,'XLK'])
SR_xlk<-m_xlk/s_xlk
varisk_xlk<-quantile(rt[,'XLK'],probs=c(0.05))
es_xlk<-ES(rt[,'XLK'],p=0.05,method='historical')
colname<-c('mean','std','SR','VaR','ES')
stats<-matrix(NA,ncol=5,nrow=11,dimnames=list(nmlist,colname))
for (i in 1:length(nmlist)){
  value<-rt[,nmlist[i]]
  m=mean(value)
  s=sd(value)
  SR=m/s
  varisk=quantile(value,probs=c(0.05))
  es=ES(value,p=0.05,method='historical')
  stats[i,1]<-m
  stats[i,2]<-s
  stats[i,3]<-SR
  stats[i,4]<-varisk
  stats[i,5]<-es
}
View(stats)
ETF8<-rt[,-which(colnames(rt)%in%c('XLK','XLE','XLF'))]
myETF<-ETF8[,which(colnames(ETF8)%in%c('XLY','XLC','XLV'))]

myETF_Series<-as.timeSeries(myETF)
specPort<-portfolioSpec()
setRiskFreeRate(specPort)<-0.08/252
minvar<-minvariancePortfolio(myETF_Series,specPort)
minvar
maxSharpe<-tangencyPortfolio(myETF_Series,specPort)
maxSharpe
